sudo: required 
services:
    # to get copy of docker
    - docker

before_install:
    - docker build -t soumya9v/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true soumya9v/docker-react npm run test -- --coverage